### ISSUE TITLE
Firefox not use proxy

### ISSUE THREAD

**Issue by Negashev** [AutomatedTester/browsermob-proxy-py#64]
I run selenium hub with firefox and proxy browsermob by [`bwowk/browsermob-proxy`](https://hub.docker.com/r/bwowk/browsermob-proxy/)

1) all in `docker-compose.yml` file
```yml
hub:
  image: selenium/hub
  ports:
    - 4444:4444
firefox:
  image: selenium/node-firefox
  links:
    - hub
    - proxy
proxy:
  image: bwowk/browsermob-proxy
  ports:
    - 58080:8080
```

2) Create a Dockerfile with `pip install selenium browsermob-proxy` and link `hub` and `proxy`

```Dockerfile
FROM python:3-alpine
RUN pip install selenium browsermob-proxy
```
in terminal write
```python
from selenium import webdriver
from browsermobproxy import Client

proxyClient = Client("proxy:8080")

proxy = proxyClient.selenium_proxy()

caps = webdriver.DesiredCapabilities.FIREFOX.copy()
proxy.add_to_capabilities(caps)

driver = webdriver.Remote(command_executor='http://hub:4444/wd/hub', desired_capabilities=caps)


proxyClient.new_har()

driver.get('http://google.com')

for ent in proxyClient.har['log']['entries']:
    print(ent['request']['url'])

proxyClient.close()
driver.quit()
```
in debug i see that var `caps` have are proxy key and in proxy server i see that new proxy is registered
![3](https://cloud.githubusercontent.com/assets/4653589/20709293/45d34dc2-b656-11e6-9003-40b05d6f8c5a.png)
![4](https://cloud.githubusercontent.com/assets/4653589/20709331/7ed5c8f2-b656-11e6-9515-6a4ad633941a.png)

But firefox does not use this proxy address. That is why i can not get logs.

`proxyClient.har['log']['entries']` is null []
